---
- name: Install Clickhouse
  hosts: clickhouse
  become: true
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  become: true
  roles:
    - vector

- name: Install nginx+epel-release
  hosts: lighthouse
  become: true
  pre_tasks:
    - block:
        - name: Install git
          ansible.builtin.yum:
            name: git
            state: latest
  roles:
    - lighthouse
