- name: Start nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted
- name: start-nginx
  become: true
  command: nginx
- name: reload-nginx
  become: true
  command: nginx -s reload