- name: Install epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy nginx configuration
  become: true
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest:  /etc/nginx/nginx.conf
    mode: '0644'
  notify: Start nginx service

- name: Lighthouse cloned
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_vcs }}"
    dest: "{{ lighthouse_dir }}" #тут была ошибка в адресе
    version: master

- name: Deploy lighthouse configuration
  become: true
  ansible.builtin.template:
    src: templates/lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: '0644'

- name: Restart nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted


