---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    vector_service: 'vector.service'
  tasks:   #проверка, что конфиг валидный, проверка успешности запуска:
    - name: 'Gather Local Services'
      ansible.builtin.service_facts:
      become: true
    - name: 'Vector service assert'
      ansible.builtin.assert:
        that:
          - "'{{ vector_service }}' in ansible_facts.services"
          - "'running' == ansible_facts.services[vector_service].state"